from python:3.9-slim

RUN apt-get update \
&& apt-get install gcc -y \
&& apt-get clean

COPY binance_exporter /app/binance_exporter/
COPY requirements.txt /app/

WORKDIR /app
EXPOSE 8080

RUN apt-get install gcc
RUN pip install -r /app/requirements.txt

CMD python -m binance_exporter.exporter
