version: '3.7'

services:
  binance-exporter:
    image: binance-exporter:0.1
    container_name: binance-exporter
    expose:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
